// Yeh aapki saari images ka data hai - direct load, no cache
export const IMAGES = [
        {
    "public_id": "🦚 Little Krishna, Bathed in Gold – Acrylic Painting 🦚",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531437/Krishna_Round_Orginal.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531437/Krishna_Round_Orginal.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531437/Krishna_Round_Display.jpg",
     ],
    "title": "🦚 Little Krishna, Bathed in Gold – Acrylic Painting 🦚",
    "category": "Spiritual Paintings",
    "price": 5100,
    "originalPrice": 7500,
    "sku": "SKU# ",
    "year": "2026",
    "size": "24 inches",
    "description": "A charming hand painted acrylic of baby Krishna glancing over his shoulder with a sweet, mischievous smile, crowned with peacock feathers and adorned with layered jewellery against a glowing golden backdrop. ✅ 100% Hand painted Acrylic on Round Canvas. ✅ Rich detailing: peacock feather crown, beaded necklaces, gold earrings & flowing blue drapes. ✅ Perfect for pooja rooms, living rooms & festive gifting, especially Janmashtami. Let the warmth of Nandlala's smile brighten your home. 🦚🙏.",
    "medium": "Acrylic on Round Canvas",
    "isSold": false,
    },
       {
    "public_id": "🦚 Divine Melody – Lord Krishna Acrylic Painting 🦚",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1788277378/Shreeji_New.jpg",
      "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1788277378/Shreeji_New.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531439/Shreeji_with_Flute_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531439/Shreeji_with_Flute_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531438/Shreeji_with_Flute_Display.jpg",
     ],
    "title": "🦚 Divine Melody – Lord Krishna Acrylic Painting 🦚",
    "category": "Spiritual Paintings",
    "price": 28000,
    "originalPrice": 36000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "30 x 36 inches",
    "description": "A vibrant hand painted acrylic capturing Lord Krishna in graceful motion, flute in hand, adorned in flowing robes of emerald, saffron and gold, crowned by a resplendent peacock-feather halo. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing — jewellery, drapery & peacock crown. ✅ Perfect for pooja rooms, living rooms & festive gifting. <br> Bring home the divine rhythm of Krishna's flute. 🪈🙏.",
    "medium": "Acrylic on Streched Canvas",
    "isSold": false
    },
     {
    "public_id": "🎶 Krishna's Serenade – Acrylic Painting 🎶",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790852987/ShriKrishna_Display2.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790852987/ShriKrishna_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531411/ShriKrishna_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531410/ShriKrishna_Display.jpg",
     ],
    "title": "🎶 Krishna's Serenade – Acrylic Painting 🎶",
    "category": "Spiritual Paintings",
    "price": 28000,
    "originalPrice": 36000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "24 x 30 inches",
    "description": "A close-up hand painted acrylic of Lord Krishna lost in his flute's melody, eyes closed in blissful devotion, adorned with roses, a peacock feather and a rudraksha mala against a warm, glowing backdrop. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing — floral crown, jewellery & flowing robes. ✅ Perfect for pooja rooms, living rooms & festive gifting. <br> Let the music of Krishna fill your space. 🪈🙏.",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false,
    },
        {
    "public_id": "🦚🐄 Krishna & His Divine Herd – Acrylic Painting 🐄🦚",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790852987/KrishanjiWithHerds_Display2.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790852987/KrishanjiWithHerds_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790852987/KrishanjiWithHerds_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790852987/KrishanjiWithHerds_Display1.jpg",
     ],
    "title": "🦚🐄 Krishna & His Divine Herd – Acrylic Painting 🐄🦚",
    "category": "Spiritual Paintings",
    "price": 32000,
    "originalPrice": 41000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "34 x 50 inches",
    "description": "A large, richly coloured hand painted acrylic of Lord Krishna playing his flute with eyes closed in serene devotion, encircled by gentle cows and calves as a golden halo glow behind him. Set against a sunset sky, a riverside ghat and a graceful chhatri, the scene brings the peace of Vrindavan to life. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: peacock feather crown, purple flower garlands, gold jewellery, and adorned cows with tender little calves. ✅ Perfect for pooja rooms, living rooms, meditation spaces & housewarming gifts. May the flute's calm and Govinda's blessings fill your home. 🪈🦚🙏.",
    "medium": "Acrylic on Canvas (Rolled)",
    "isSold": false,
    },
        {
    "public_id": "✨ Krishna's Divine Radiance – Acrylic Painting ✨",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696524/Divine_Krishna_Blue_Original.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696524/Divine_Krishna_Blue_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696784/Divine_Krishna_Blue_Display1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696522/Divine_Krishna_Blue_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696522/Divine_Krishna_Blue_Display3.jpg",
     ],
    "title": "✨ Krishna's Divine Radiance – Acrylic Painting ✨",
    "category": "Spiritual Paintings",
    "price": 32000,
    "originalPrice": 41000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "34 x 50 inches",
    "description": "A majestic hand painted acrylic of Lord Krishna standing in his graceful tribhanga pose, playing the flute in flowing royal blue robes with a peacock feather crown. Set against golden rays of light and surrounded by glowing diyas on a lotus pedestal, the piece radiates warmth, devotion and divine grace. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: peacock feather turban, gold jewellery, flower garland & flowing brocade-edged robes. ✅ Perfect for pooja rooms, living rooms, meditation spaces & festive gifting. May Krishna's divine light brings peace and blessings to your home. 🪔🙏.",
    "medium": "Acrylic on Canvas - Rolled",
    "isSold": false,
    },
    {
    "public_id": "🧩 Earth Geometry – Abstract Oil Painting 🧩",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790612493/Oil_Abstract_Original1.jpg",
      "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790612493/Oil_Abstract_Original1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531436/Oil_Abstract_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531437/Oil_Abstract_Display.jpg",
     ],
    "title": "🧩 Earth Geometry – Abstract Oil Painting 🧩",
    "category": "Abstract Paintings",
    "price": 15000,
    "originalPrice": 23000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "18 x 24 inches",
    "description": "A bold hand painted abstract in oil, where interlocking shapes, sweeping arcs and layered blocks come together in a warm palette of terracotta, ochre and muted olive green. The textured surface and glowing pale edges give the composition depth, like a puzzle waiting to be read. ✅ 100% Hand painted Oil on Canvas, 18 x 24 inch. ✅ Rich detailing: textured layers, curved motifs & earthy tones with soft green accents. ✅ Perfect for living rooms, offices, studios, cafes & modern or contemporary interiors. Let this study in shape and colour add character to your walls. 🎨✨.",
    "medium": "Oil on Canvas - Rolled",
    "isSold": false
    },
        {
    "public_id": "🍺 Cheers in Colour – Acrylic Painting 🍺",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696526/Beer_Original.jpg",
      "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696526/Beer_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696525/Beer_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696525/Beer_Display1.jpg",
     ],
    "title": "🍺 Cheers in Colour – Acrylic Painting 🍺",
    "category": "Still Paintings",
    "price": 2800,
    "originalPrice": 5000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "12 x 16 inches",
    "description": "A vibrant hand painted acrylic still life capturing a frothy mug of beer garnished with a bright orange slice, painted in bold, expressive brushstrokes. Juicy lemon wheels, deep red fruit and a resting hand bring warmth and life to the composition, turning a simple drink into a celebration of colour. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: loose expressive brushwork, citrus textures & a lively warm palette. ✅ Perfect for kitchens, bar corners, dining spaces, cafes & pubs. A toast to good company, painted in bold colour. 🍋🎨.",
    "medium": "Acrylic on Streched Canvas",
    "isSold": false
    },
        {
    "public_id": "☕ The Perfect Dip – Acrylic Painting ☕",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696526/Biscuit_Dip_Original.jpg",
      "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696526/Biscuit_Dip_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696526/Biscuit_Dip_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696525/Biscuit_Dip_Display1.jpg",
     ],
    "title": "☕ The Perfect Dip – Acrylic Painting ☕",
    "category": "Still Paintings",
    "price": 2800,
    "originalPrice": 5000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "12 x 16 inches",
    "description": "A warm, expressive hand painted acrylic capturing the simple joy of dunking a biscuit into a steaming cup of coffee. Bold brushstrokes and a rich palette of teal, maroon and burnt orange turn an everyday ritual into a cosy, colourful moment. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: loose expressive brushwork, glossy cup textures & a vibrant contrasting background. ✅ Perfect for kitchens, dining spaces, cafes & breakfast nooks. A little pause, a warm cup, a favourite biscuit. ☕🍪.",
    "medium": "Acrylic on Streched Canvas",
    "isSold": false
    },
        {
    "public_id": "🌿 Fresh & Fizzy – Acrylic Painting 🌿",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696524/Mojito_Original.jpg",
      "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696524/Mojito_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696522/Mojito_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790701979/Mojito_Display1.jpg",
     ],
    "title": "🌿 Fresh & Fizzy – Acrylic Painting 🌿",
    "category": "Still Paintings",
    "price": 2800,
    "originalPrice": 5000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "12 x 16 inches",
    "description": "A vivid hand painted acrylic still life of a refreshing drink, garnished with a lime wheel and fresh mint sprigs, set against an electric pink and teal backdrop. Bold, expressive brushstrokes turn a simple glass into a burst of colour and energy. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: sunburst lime slice, loose mint sprigs & a vibrant contrasting background. ✅ Perfect for bar corners, kitchens, patios, cafes & summery interiors. A splash of colour to keep the good times going. 🍋🎨.",
    "medium": "Acrylic on Streched Canvas",
    "isSold": false
    },
        {
    "public_id": "🌿 Mojito Overflow – Acrylic Painting 🌿",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696524/Mojito_Gin_Original.jpg",
      "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696524/Mojito_Gin_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696523/Mojito_Gin_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696522/Mojito_Gin_Display1.jpg",
     ],
    "title": "🌿 Mojito Overflow – Acrylic Painting 🌿",
    "category": "Still Paintings",
    "price": 2800,
    "originalPrice": 5000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "12 x 16 inches",
    "description": "A lush, close-up hand painted acrylic bursting with mint leaves spilling over a glass, paired with a fresh lime wedge in the foreground. Set against a moody purple-blue backdrop, the vivid greens and warm oranges create a lively, textured composition full of movement. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: layered mint leaves, sunburst lime wedge & a rich contrasting backdrop. ✅ Perfect for bar corners, kitchens, patios, cafes & summery interiors. Fresh, fizzy and full of life. 🍈🎨.",
    "medium": "Acrylic on Streched Canvas",
    "isSold": false
    },
        {
    "public_id": "🫐 Stack of Sunshine – Acrylic Painting 🫐",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696525/Pancake_Original.jpg",
      "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696525/Pancake_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696524/Pancake_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790696524/Pancake_Display1.jpg",
     ],
    "title": "🫐 Stack of Sunshine – Acrylic Painting 🫐",
    "category": "Still Paintings",
    "price": 2800,
    "originalPrice": 5000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "12 x 16 inches",
    "description": "A juicy, appetising hand painted acrylic of a towering pancake stack, dripping with syrup and heaped with plump blueberries. Bold orange and gold tones against a cool blue plate give the piece a warm, sunny energy that celebrates a favourite comfort food. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: glistening syrup drips, layered pancake texture & juicy blueberry clusters. ✅ Perfect for kitchens, dining spaces, cafes & breakfast nooks. Sweet, golden and always a good morning. 🥞☀️.",
    "medium": "Acrylic on Streched Canvas",
    "isSold": false
    },
    {
    "public_id": "👑 Shrinathji – Divine Acrylic Painting 👑",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790854378/Shreenath_Display2.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790854378/Shreenath_Display2.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790854215/Shreenath_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790531435/Shreenath_Display.jpg",
     ],
    "title": "👑 Shrinathji – Divine Acrylic Painting 👑",
    "category": "Spiritual Paintings",
    "price": 2800,
    "originalPrice": 5000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "12 x 16 inches",
    "description": "A radiant hand painted acrylic of Lord Shrinathji, his deep blue face adorned with an ornate golden crown, peacock feather and layered pearl-and-gold jewellery, set against a warm terracotta backdrop with lotus blooms in full flower. ✅ 100% Hand painted Acrylic on Canvas. ✅ Intricate detailing — royal crown, jewellery & peacock feather. ✅ Rich, warm palette with striking traditional motifs. ✅ Perfect for pooja rooms, living rooms & devotional gifting. Divine grace, painted with devotion. 🪷🙏.",
    "medium": "Acrylic on Streched Canvas",
    "isSold": false
    },
     {
    "public_id": "🕊️ Whispers of Freedom – Acrylic Painting 🕊️",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/f_auto,q_auto/IMG_20240406_173546",
    "title": "🕊️ Whispers of Freedom – Acrylic Painting 🕊️",
    "category": "Figurative Paintings",
    "price": 5000,
    "originalPrice": 7800,
    "sku": "SKU# ",
    "year": "2025",
    "size": "14 x 18 inches",
    "description": "A striking handpainted acrylic portrait of a woman in quiet profile, crowned by a majestic white dove with outstretched wings, surrounded by flitting red birds and lush green vines against a muted sage backdrop. A poetic blend of realism and symbolism. ✅ 100% Handpainted Acrylic on Canvas. ✅ Fine detailing — realistic portrait meets stylized birds. ✅ Soft, earthy palette with striking red accents. ✅ Perfect for living rooms, study spaces & contemporary art collectors. A quiet gaze, a soul set free. 🌿🎨",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
    },
    {
    "public_id": "🌌 Cosmic Krishna – Acrylic Painting 🌌",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1787921850/Cosmic_Krishna.jpg",
    "title": "🌌 Cosmic Krishna – Acrylic Painting 🌌",
    "category": "Spiritual Paintings",
    "price": 15000,
    "originalPrice": 23000,
    "sku": "SKU# ",
    "year": "2026",
    "size": "24 x 36 inches",
    "description": "A breathtaking handpainted acrylic of Lord Krishna playing his flute amidst a celestial sky, wrapped in swirling clouds with planets, stars and a glowing golden halo. A vision where divinity meets the infinite universe. ✨ 100% Handpainted Acrylic on Canvas. ✨ Stunning cosmic theme — galaxies, planets & celestial clouds. ✨ Rich gold detailing against deep blue tones. ✨ Perfect for living rooms, meditation spaces & statement walls. ✨ Where the divine meets the infinite. ✨🪈",
    "medium": "Acrylic on Canvas",
    "isSold": true
    },
    {
    "public_id": "Wild Flower",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1778648320/motion_photo_4398328002698571652_jxmvau.jpg",
    "title": "Wild Flower",
    "category": "Floral Paintings",
    "price": 3999,
    "originalPrice": 6999,
    "sku": "SKU# ",
    "year": "",
    "size": "18 x 30 inches",
    "description": "Medium-Oil on Canvas Paper",
    "medium": "Oil on Canvas Paper - Rolled",
    "isSold": false
    },
    {
    "public_id": "Acrytlic Painting",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/q_auto/f_auto/v1775055027/IMG-20260401-WA0007_mxrpbp.jpg",
    "title": "🏮 Glowing Lantern – Acrylic Painting 🏮",
    "category": "Still Paintings",
    "price": 3200,
    "originalPrice": 6000,
    "sku": "SKU# ",
    "year": 2026,
    "size": "16 x 20 inches",
    "description": "A striking hand painted acrylic of a vintage red lantern glowing warmly amidst a forest of blue-green trees and golden autumn leaves. Bold, expressive brushstrokes bring a cozy, nostalgic warmth against a cool woodland backdrop. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich contrast of warm reds & golds against cool blues & greens. ✅ Expressive, textured brushwork with striking detail. ✅ Perfect for living rooms, cozy corners & rustic-themed spaces. <br> A glow that lights up any wall. 🍂🎨.",
    "medium": "Acrylic on Canvas",
    "isSold": false
  },
  {
    "public_id": "Sunset_Beach",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772821278/IMG-20260306-WA0025_cozmpa.jpg",
    "title": "Sunset Beach",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# ",
    "year": 2024,
    "size": "08 x 10 inches",
    "description": "Acrylic On Canvas board - Framed",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": true
  },
  {
    "public_id": "Snowfall",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772821244/IMG-20260306-WA0024_koguvj.jpg",
    "title": "Snowfall",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# ",
    "year": 2024,
    "size": "08 x 10 inches",
    "description": "Acrylic On Canvas board - Framed",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": true
  },
  {
    "public_id": "Sunset",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772821121/IMG-20260306-WA0023_secxez.jpg",
    "title": "Sunset",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# ",
    "year": 2024,
    "size": "12 x 12 inches",
    "description": "Acrylic On Canvas Board - Framed",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": true
  },
  {
    "public_id": "Sailboat",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772818820/IMG-20260303-WA0013_wwxs1y.jpg",
    "title": "Sailboat",
    "category": "Still Paintings",
    "price": 2800,
    "originalPrice": 6000,
    "sku": "SKU# ",
    "year": 2026,
    "size": "18 x 18 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0006_Bright_Snowy_Autumn_Landscape_qstoj7",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--3KRMZFnB--/c_limit,w_1200/q_auto/f_auto/A0006_Bright_Snowy_Autumn_Landscape_qstoj7?_a=BAMAOGUs0",
    "title": "Bright Snowy Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0006",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0007_Cabin_in_a_Snowy_Landscape_ovfx9h",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--SRS9EUmY--/c_limit,w_1200/q_auto/f_auto/A0007_Cabin_in_a_Snowy_Landscape_ovfx9h?_a=BAMAOGUs0",
    "title": "Cabin in a Snowy Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0007",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0008_Wooden_Bridge_in_a_Snowy_Landscape_m2snny",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--k-IcpIvl--/c_limit,w_1200/q_auto/f_auto/A0008_Wooden_Bridge_in_a_Snowy_Landscape_m2snny?_a=BAMAOGUs0",
    "title": "Wooden Bridge in a Snowy Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0008",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0009_Snowy_Night_Landscape_nn0myi",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--vUOjCpdM--/c_limit,w_1200/q_auto/f_auto/A0009_Snowy_Night_Landscape_nn0myi?_a=BAMAOGUs0",
    "title": "Snowy Night Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0009",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0010_Log_Bridge_Autumn_Landscape_owgs30",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Q52v9gul--/c_limit,w_1200/q_auto/f_auto/A0010_Log_Bridge_Autumn_Landscape_owgs30?_a=BAMAOGUs0",
    "title": "Log Bridge Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0010",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0011_Full_Moon_Autumn_Landscape_prpnub",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--X_pZOnJW--/c_limit,w_1200/q_auto/f_auto/A0011_Full_Moon_Autumn_Landscape_prpnub?_a=BAMAOGUs0",
    "title": "Full Moon Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0011",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0012_Beautiful_Mountain_Landscape_kvvsxo",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Hvvbzzd1--/c_limit,w_1200/q_auto/f_auto/A0012_Beautiful_Mountain_Landscape_kvvsxo?_a=BAMAOGUs0",
    "title": "Beautiful Mountain Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0012",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0013_Beach_Landscape_nt4gcn",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--r5ku7INw--/c_limit,w_1200/q_auto/f_auto/A0013_Beach_Landscape_nt4gcn?_a=BAMAOGUs0",
    "title": "Beach Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0013",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0014_Road_along_the_Humongous_Trees_mpojk4",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--kwMqXIp3--/c_limit,w_1200/q_auto/f_auto/A0014_Road_along_the_Humongous_Trees_mpojk4?_a=BAMAOGUs0",
    "title": "Road along the Humongous Trees",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0014",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0015_Thatched_House_Landscape_estxhy",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--oEdzTajP--/c_limit,w_1200/q_auto/f_auto/A0015_Thatched_House_Landscape_estxhy?_a=BAMAOGUs0",
    "title": "Thatched House Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0015",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0016_A_Girl_in_a_Rainy_Night_l9qvai",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--i4f8R2sZ--/c_limit,w_1200/q_auto/f_auto/A0016_A_Girl_in_a_Rainy_Night_l9qvai?_a=BAMAOGUs0",
    "title": "A Girl in a Rainy Night",
    "category": "Figurative Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0016",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0017_Lighthouse_Along_the_Bay_dwkzhe",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--5CTWppkf--/c_limit,w_1200/q_auto/f_auto/A0017_Lighthouse_Along_the_Bay_dwkzhe?_a=BAMAOGUs0",
    "title": "Lighthouse Along the Bay",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0017",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0018_Bright_Green_Landscape_with_a_Beautiful_Swan_x0vpns",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--2BczoTRw--/c_limit,w_1200/q_auto/f_auto/A0018_Bright_Green_Landscape_with_a_Beautiful_Swan_x0vpns?_a=BAMAOGUs0",
    "title": "Bright Green Landscape with a Beautiful Swan",
    "category": "Animal Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0018",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0019_Artistic_Flamingo_dal3pg",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--ckgFXCfW--/c_limit,w_1200/q_auto/f_auto/A0019_Artistic_Flamingo_dal3pg?_a=BAMAOGUs0",
    "title": "Artistic Flamingo",
    "category": "Animal Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0019",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0020_Vibrant_Peaceful_Swan_m0r4ke",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--cXBikGfO--/c_limit,w_1200/q_auto/f_auto/A0020_Vibrant_Peaceful_Swan_m0r4ke?_a=BAMAOGUs0",
    "title": "Vibrant Peaceful Swan",
    "category": "Animal Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0020",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0021_Autumn_Landscape_with_a_Running_Happy_Dog_hk2bwa",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--zLYHQzkX--/c_limit,w_1200/q_auto/f_auto/A0021_Autumn_Landscape_with_a_Running_Happy_Dog_hk2bwa?_a=BAMAOGUs0",
    "title": "Autumn Landscape with a Running Happy Dog",
    "category": "Animal Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0021",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0022_Full_Moon_Snowy_Landscape_axd9oj",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--4sAvjkK1--/c_limit,w_1200/q_auto/f_auto/A0022_Full_Moon_Snowy_Landscape_axd9oj?_a=BAMAOGUs0",
    "title": "Full Moon Snowy Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0022",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0023_Snowy_Landscape_1_e0rul8",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--9R1AEEnp--/c_limit,w_1200/q_auto/f_auto/A0023_Snowy_Landscape_1_e0rul8?_a=BAMAOGUs0",
    "title": "Snowy Landscape 1",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0023",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0024_Snowy_Landscape_2_pfnttq",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--HeWzV2ju--/c_limit,w_1200/q_auto/f_auto/A0024_Snowy_Landscape_2_pfnttq?_a=BAMAOGUs0",
    "title": "Snowy Landscape 2",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0024",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0025_Snowy_Waterfall_Landscape_xpp3dy",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--bZldfgIH--/c_limit,w_1200/q_auto/f_auto/A0025_Snowy_Waterfall_Landscape_xpp3dy?_a=BAMAOGUs0",
    "title": "Snowy Waterfall Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0025",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0026_Snowy_Autumn_Landscape_gi57gn",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--0O7SwP7T--/c_limit,w_1200/q_auto/f_auto/A0026_Snowy_Autumn_Landscape_gi57gn?_a=BAMAOGUs0",
    "title": "Snowy Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0026",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0027_Snowy_Full_Moon_Autumn_Landscape_xensc4",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--n1OmjWEh--/c_limit,w_1200/q_auto/f_auto/A0027_Snowy_Full_Moon_Autumn_Landscape_xensc4?_a=BAMAOGUs0",
    "title": "Snowy Full Moon Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0027",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0028_Pink_Water_Lily_aums8g",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--xAm6dhZS--/c_limit,w_1200/q_auto/f_auto/A0028_Pink_Water_Lily_aums8g?_a=BAMAOGUs0",
    "title": "Pink Water Lily",
    "category": "Floral Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0028",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "🍓 The Strawberry – Acrylic Painting 🍓",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790326/Strawberry_Display1.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790326/Strawberry_Display1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790333/Strawberry_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790325/Strawberry_Display2.jpg",
     ],
    "title": "🍓 The Strawberry – Acrylic Painting 🍓",
    "category": "Still Paintings",
    "price": 2300,
    "originalPrice": 4500,
    "sku": "SKU# A0029",
    "year": 2026,
    "size": "12 x 12 inches",
    "description": "A juicy hand painted acrylic of a chocolate-dipped strawberry, its leafy green crown fanning out against a warm, fiery orange backdrop. Part of a playful still-life series that turns everyday snacks into striking pop-art studies. ✅ 100% Hand painted Acrylic on Canvas.✅ Rich detailing: glossy chocolate dip, textured seeds & a bold red-orange contrast. ✅ Perfect for kitchens, cafes, bar corners & bold modern interiors. Sweet, juicy and full of life. ❤️🎨.",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "🍩 The Donut – Acrylic Painting 🍩",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790338/Donut_Display1.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790338/Donut_Display1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790337/Donut_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790338/Donut_Display2.jpg",
     ], "title": "🍩 The Donut – Acrylic Painting 🍩",
    "category": "Still Paintings",
    "price": 2300,
    "originalPrice": 4500,
    "sku": "SKU# A0030",
    "year": 2026,
    "size": "10 x 12 inches",
    "description": "A vivid hand painted acrylic of a pink glazed donut, drizzled with white icing and a touch of chocolate, set against a bold magenta-purple backdrop. Part of a playful still-life series that turns everyday snacks into striking pop-art studies. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: glossy glaze drips, soft highlights & a bold pink-purple contrast. ✅ Perfect for kitchens, cafes, bar corners & bold modern interiors. Sweet, playful and full of colour. 💗🎨.",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "🥠 The Fortune Cookie – Acrylic Painting 🥠",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790339/Fortune_Cookie_Display1.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790339/Fortune_Cookie_Display1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790336/Fortune_Cookie_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790339/Fortune_Cookie_Display2.jpg",
     ],"title": "🥠 The Fortune Cookie – Acrylic Painting 🥠",
    "category": "Still Paintings",
    "price": 2300,
    "originalPrice": 4500,
    "sku": "SKU# A0031",
    "year": 2026,
    "size": "12 x 12 inches",
    "description": "A bold hand painted acrylic of a single fortune cookie in warm amber and gold, set against a vivid teal backdrop with graphic navy and orange accents. Part of a playful still-life series that turns everyday snacks into striking pop-art studies. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: folded cookie texture, warm highlights & a bold teal-orange contrast. ✅ Perfect for kitchens, cafes, bar corners & bold modern interiors. A small treat, painted with big colour. 🧡🎨.",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "🥨 The Pretzel – Acrylic Painting 🥨",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790326/The_Pretzel_Display1.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790326/The_Pretzel_Display1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790337/The_Pretzel_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790338/The_Pretzel_Display2.jpg",
     ], "title": "🥨 The Pretzel – Acrylic Painting 🥨",
    "category": "Still Paintings",
    "price": 2300,
    "originalPrice": 4500,
    "sku": "SKU# A0032",
    "year": 2026,
    "size": "10 x 12 inches",
    "description": "A striking hand painted acrylic of a classic salted pretzel, rendered in unexpected dark olive and warm amber tones against a vivid violet-magenta backdrop. The bold colour choices and graphic composition give an everyday snack a playful, gallery-worthy presence. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: glistening salt crystals, twisted dough texture & a striking purple-orange contrast. ✅ Perfect for kitchens, cafes, bar corners & bold modern interiors. A snack, elevated into art. 🧡🎨.",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "🍊 The Popsicle – Acrylic Painting 🍊",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790340/The_Popsicle_Display1.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790340/The_Popsicle_Display1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790337/The_Popsicle_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790328/The_Popsicle_Display2.jpg",
     ],"title": "🍊 The Popsicle – Acrylic Painting 🍊",
    "category": "Still Paintings",
    "price": 2300,
    "originalPrice": 4500,
    "sku": "SKU# A0033",
    "year": 2026,
    "size": "10 x 12 inches",
    "description": "A bold, sun-soaked hand painted acrylic of a single orange popsicle resting diagonally against a rich teal backdrop. The graphic composition and juicy citrus tones give it a playful, pop-art feel, capturing the simple pleasure of a summer treat. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: glossy melt-drip highlights, ribbed popsicle texture & a punchy teal-orange contrast. ✅ Perfect for kitchens, kids' rooms, cafes & bright modern interiors. A sweet, sunny bite of nostalgia. 🧡☀️.",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "☕ The Coffee Cup – Acrylic Painting ☕",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790328/Coffee_Cup_Display1.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790328/Coffee_Cup_Display1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790346/Coffee_Cup_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790337/Coffee_Cup_Display2.jpg",
     ], "title": "☕ The Coffee Cup – Acrylic Painting ☕",
    "category": "Still Paintings",
    "price": 1600,
    "originalPrice": 2800,
    "sku": "SKU# A0034",
    "year": 2026,
    "size": "10 x 12 inches",
    "description": "A warm hand painted acrylic of a latte in a vivid green cup, its foam swirled into a soft heart shape against rich mocha tones. Part of a playful still-life series that turns everyday treats into striking pop-art studies. ✅ 100% Hand painted Acrylic on Canvas, framed. ✅ Rich detailing: swirling latte art, glossy ceramic highlights & a bold green-violet contrast. ✅ Perfect for kitchens, cafes, bar corners & bold modern interiors. A warm cup, a little bit of love. ☕💚.",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "🍊 The Sliced Oranges – Acrylic Painting 🍊",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790327/Sliced_Oranges_Display1.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790327/Sliced_Oranges_Display1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790341/Sliced_Oranges_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790325/Sliced_Oranges_Display2.jpg",
     ], "title": "🍊 The Sliced Oranges – Acrylic Painting 🍊",
    "category": "Still Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0035",
    "year": 2026,
    "size": "10 x 10 inches",
    "description": "A juicy hand painted acrylic still life of a fresh orange sliced open to reveal its starburst centre, paired with a bright lime and cool blue backdrop. Part of a playful still-life series that turns everyday treats into striking pop-art studies. ✅ 100% Hand painted Acrylic on Canvas, framed. ✅ Rich detailing: starburst citrus pattern, glossy peel highlights & a fresh orange-blue contrast. ✅ Perfect for kitchens, cafes, bar corners & bold modern interiors. Fresh, juicy and bursting with colour. 🍋🎨.",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "👠 Her Favourite Pair – Acrylic Painting 👠",
    "url": "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790340/High_Heels_Display1.jpg",
    "images": [
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790340/High_Heels_Display1.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790343/High_Heels_Original.jpg",
       "https://res.cloudinary.com/eez1bs5e/image/upload/v1790790339/High_Heels_Display2.jpg",
     ],
    "title": "👠 Her Favourite Pair – Acrylic Painting 👠",
    "category": "Still Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0036",
    "year": 2026,
    "size": "8 x 8 inches",
    "description": "A chic hand painted acrylic still life of a pair of pointed stiletto heels in warm caramel tones, set against a dreamy wash of pink and lavender. Loose, confident brushstrokes give the shoes a sense of movement and glamour, celebrating everyday elegance. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich detailing: glossy leather highlights, sculpted heel curves & a soft pastel backdrop. ✅ Perfect for dressing rooms, bedrooms, walk-in closets & boutiques. A little luxury, captured in colour. 👠💅.",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0037_Pink_Tulip_yw8df5",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--KR3TjUB9--/c_limit,w_1200/q_auto/f_auto/A0037_Pink_Tulip_yw8df5?_a=BAMAOGUs0",
    "title": "🌹 Blooming Passion – Framed Acrylic Painting 🌹",
    "category": "Floral Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0037",
    "year": 2026,
    "size": "10 x 10 inches",
    "description": "A vivid close-up hand painted acrylic of a peony rose in full bloom, its ruffled crimson and pink petals unfolding around a golden center, set against a rich tapestry of emerald and teal foliage. Elegantly framed in black, ready to hang. ✅ 100% Hand painted Acrylic on Canvas. ✅ Bold, layered petals in rich pinks & reds. ✅ Comes ready-to-hang in a sleek black frame. ✅ Perfect for living rooms, bedrooms & romantic accent walls. A rose that never wilts. 🌿🎨",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0038_Cone_Flower_t8fnje",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--ddM7p8kY--/c_limit,w_1200/q_auto/f_auto/A0038_Cone_Flower_t8fnje?_a=BAMAOGUs0",
    "title": "Cone Flower",
    "category": "Floral Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0038",
    "year": 2026,
    "size": "10 x 10 inches",
    "description": "Acrylic on Canvas (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0039_White_Lily_tohvti",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--qQbRaTHo--/c_limit,w_1200/q_auto/f_auto/A0039_White_Lily_tohvti?_a=BAMAOGUs0",
    "title": "White Lily",
    "category": "Floral Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0039",
    "year": 2026,
    "size": "12 x 12 inches",
    "description": "Acrylic on Canvas (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0040_The_Red_Dahlia_puimyq",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--lNXRLV6i--/c_limit,w_1200/q_auto/f_auto/A0040_The_Red_Dahlia_puimyq?_a=BAMAOGUs0",
    "title": "The Red Dahlia",
    "category": "Floral Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0040",
    "year": 2026,
    "size": "12 x 12 inches",
    "description": "Acrylic on Canvas (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0041_Zinnia_Floral_Painting_tiemlp",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--ZLnlZrSr--/c_limit,w_1200/q_auto/f_auto/A0041_Zinnia_Floral_Painting_tiemlp?_a=BAMAOGUs0",
    "title": "Zinnia Flower",
    "category": "Floral Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0041",
    "year": 2026,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0041_The_Lady_with_a_Hat_Abstract_lsopgv",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--tKggpmQS--/c_limit,w_1200/q_auto/f_auto/A0041_The_Lady_with_a_Hat_Abstract_lsopgv?_a=BAMAOGUs0",
    "title": "The Lady with a Hat (Abstract)",
    "category": "Abstract Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0042",
    "year": 2025,
    "size": "10 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0043_Serene_Buddha.heic_nvxg8g",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--RMbp9JFZ--/c_limit,w_1200/q_auto/f_auto/A0043_Serene_Buddha.heic_nvxg8g?_a=BAMAOGUs0",
    "title": "🪷 Tranquil Buddha – Original Acrylic Painting 🪷",
    "category": "Spiritual Paintings",
    "price": 6000,
    "originalPrice": 10000,
    "sku": "SKU# A0043",
    "year": 2026,
    "size": "16 x 24 inches",
    "description": "A masterpiece of calm. This hand painted acrylic artwork features a meditative Buddha rendered in mesmerizing shades of jade and emerald, set against a golden-green canvas alive with blooming lotus flowers — nature's own symbol of purity and rebirth. Every brushstroke breathes stillness. Every lotus petal whispers peace. ✅ 100% Hand painted Acrylic on Canvas. ✅ Rich texture, vibrant detail, gallery-quality finish. ✅ Radiates positive energy — ideal for living rooms, entryways, offices & meditation spaces. ✅ A timeless gift for housewarmings, weddings & special occasions. This isn't just wall art — it's a daily reminder to breathe, pause, and find your center. 🙏✨.",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },

  {
    "public_id": "A0045_Golden_Sun_Landscape_a8hzsx",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Sucg6XYv--/c_limit,w_1200/q_auto/f_auto/A0045_Golden_Sun_Landscape_a8hzsx?_a=BAMAOGUs0",
    "title": "Golden Sun Landscape",
    "category": "Landscape Paintings",
    "price": 9500,
    "originalPrice": 15000,
    "sku": "SKU# A0045",
    "year": 2026,
    "size": "18 x 28 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "A0046_An_Abstract_Textured_Painting_rpeel0",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--tj2AWtok--/c_limit,w_1200/q_auto/f_auto/A0046_An_Abstract_Textured_Painting_rpeel0?_a=BAMAOGUs0",
    "title": "An Abstract Textured Painting",
    "category": "Abstract Paintings",
    "price": 3200,
    "originalPrice": 6000,
    "sku": "SKU# A0046",
    "year": 2026,
    "size": "18 x 18 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "A0047_The_Pyramids_of_Egypt_zh0ceg",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--zhf7cgLt--/c_limit,w_1200/q_auto/f_auto/A0047_The_Pyramids_of_Egypt_zh0ceg?_a=BAMAOGUs0",
    "title": "The Pyramids of Egypt",
    "category": "Landscape Paintings",
    "price": 2800,
    "originalPrice": 5000,
    "sku": "SKU# A0047",
    "year": 2026,
    "size": "12 x 16 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "A0048_The_Tree_Lined_Street_Painting_tmnzwt",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Yg0hdeFJ--/c_limit,w_1200/q_auto/f_auto/A0048_The_Tree_Lined_Street_Painting_tmnzwt?_a=BAMAOGUs0",
    "title": "The Tree Lined Street Painting",
    "category": "Landscape Paintings",
    "price": 6000,
    "originalPrice": 8600,
    "sku": "SKU# A0048",
    "year": 2026,
    "size": "18 x 24 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "A0049_The_Tree_Perspective_Painting_p0xwls",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Uo-9V5Gf--/c_limit,w_1200/q_auto/f_auto/A0049_The_Tree_Perspective_Painting_p0xwls?_a=BAMAOGUs0",
    "title": "The Tree Perspective Painting",
    "category": "Landscape Paintings",
    "price": 5000,
    "originalPrice": 8600,
    "sku": "SKU# A0049",
    "year": 2026,
    "size": "16 x 20 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "A0050_The_Sunflower_Painting_ec69vd",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Q_5iu05i--/c_limit,w_1200/q_auto/f_auto/A0050_The_Sunflower_Painting_ec69vd?_a=BAMAOGUs0",
    "title": "🌻 Sunflower Radiance – Round Acrylic Painting 🌻",
    "category": "Floral Paintings",
    "price": 10000,
    "originalPrice": 16000,
    "sku": "SKU# A0050",
    "year": 2026,
    "size": "24 inch Diameter",
    "description": "A bold, close-up hand painted acrylic of blooming sunflowers rendered in vivid golds and warm browns, set against a striking electric-blue backdrop with hints of magenta. Loose, expressive brushstrokes give this piece an energetic, sun-drenched feel on a unique circular canvas. ✅ 100% Hand painted Acrylic on Canvas. ✅ Vibrant palette — sunny yellows against vivid blues. ✅ Unique round canvas format — a bold, modern statement piece. ✅ Perfect for living rooms, kitchens & sunlit corners. A burst of sunshine for any wall. ☀️🎨",            
    "medium": "Acrylic on Stretched Round Canvas",
    "isSold": false
  },
  {
    "public_id": "A0051_The_Spring_Lily_Painting_tjmqey",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--VwHtNajo--/c_limit,w_1200/q_auto/f_auto/A0051_The_Spring_Lily_Painting_tjmqey?_a=BAMAOGUs0",
    "title": "🌸 White Lily in Bloom – Round Acrylic Painting 🌸",
    "category": "Floral Paintings",
    "price": 10000,
    "originalPrice": 16000,
    "sku": "SKU# A0051",
    "year": 2026,
    "size": "24 inch Diameter",
    "description": "A striking hand painted acrylic of a white lily in full bloom, rendered in bold contrasting strokes against a deep, moody backdrop of teal and forest greens. The vivid pops of yellow and crimson at its center bring the flower to life on this eye-catching circular canvas. ✅ 100% Hand painted Acrylic on Canvas. ✅ Unique round canvas format — a modern statement piece. ✅ Bold, vibrant palette that pops on any wall. ✅ Perfect for living rooms, entryways & contemporary spaces. A fresh, artistic bloom that never fades. 🌿🎨.",
    "medium": "Acrylic on Stretched Round Canvas",
    "isSold": false
  },
  {
    "public_id": "A0052_The_Ranunculus_Bouquete_gofc69",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--rf1C1L93--/c_limit,w_1200/q_auto/f_auto/A0052_The_Ranunculus_Bouquete_gofc69?_a=BAMAOGUs0",
    "title": "The Ranunculus Bouquete",
    "category": "Floral Paintings",
    "price": 15000,
    "originalPrice": 23000,
    "sku": "SKU# A0052",
    "year": 2026,
    "size": "30 x 30 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Canvas - Rolled",
    "isSold": false
  },
  {
    "public_id": "A0053_Vibrant_Tree_Painting_1_papeds",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--BP1HFUdl--/c_limit,w_1200/q_auto/f_auto/A0053_Vibrant_Tree_Painting_1_papeds?_a=BAMAOGUs0",
    "title": "Vibrant Tree Painting 1",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0053",
    "year": 2026,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0054_Vibrant_Tree_Painting_2_tuqxy5",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--azkOryhN--/c_limit,w_1200/q_auto/f_auto/A0054_Vibrant_Tree_Painting_2_tuqxy5?_a=BAMAOGUs0",
    "title": "Vibrant Tree Painting 2",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0054",
    "year": 2026,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0055_Frozen_Waterfall_gvbzyn",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--BG8I1TU2--/c_limit,w_1200/q_auto/f_auto/A0055_Frozen_Waterfall_gvbzyn?_a=BAMAOGUs0",
    "title": "Frozen Waterfall",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0055",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0056_Forest_Landscape_aqjaxx",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--iBxTfGJA--/c_limit,w_1200/q_auto/f_auto/A0056_Forest_Landscape_aqjaxx?_a=BAMAOGUs0",
    "title": "Forest Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0056",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0057_Antelope_Looking_at_You_zqcsge",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--MXXROuCG--/c_limit,w_1200/q_auto/f_auto/A0057_Antelope_Looking_at_You_zqcsge?_a=BAMAOGUs0",
    "title": "Antelope Looking at You",
    "category": "Animal Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0057",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0058_Autumn_Landscape_jts79a",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--fYEXlQ48--/c_limit,w_1200/q_auto/f_auto/A0058_Autumn_Landscape_jts79a?_a=BAMAOGUs0",
    "title": "Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0058",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": true
  },
  {
    "public_id": "A0059_Autumn_Orange_Tree_bt2fgn",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--CKanEFKf--/c_limit,w_1200/q_auto/f_auto/A0059_Autumn_Orange_Tree_bt2fgn?_a=BAMAOGUs0",
    "title": "Autumn Orange Tree",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0059",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0060_Autumn_Trees_Lines_ji5umh",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--H3Hlmw5i--/c_limit,w_1200/q_auto/f_auto/A0060_Autumn_Trees_Lines_ji5umh?_a=BAMAOGUs0",
    "title": "Autumn Trees Lines",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0060",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0061_Beautiful_Sunset_Landscape_ohuhrv",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--9qUuuYsP--/c_limit,w_1200/q_auto/f_auto/A0061_Beautiful_Sunset_Landscape_ohuhrv?_a=BAMAOGUs0",
    "title": "Beautiful Sunset Landscape",
    "category": "Landscape Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0061",
    "year": 2025,
    "size": "12 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0062_Lakeview_Landscape_o9v5ai",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--4Y-DU_H6--/c_limit,w_1200/q_auto/f_auto/A0062_Lakeview_Landscape_o9v5ai?_a=BAMAOGUs0",
    "title": "Lakeview Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0062",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0063_Landscape_Sunrise_jccqpz",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--LllaW1Ml--/c_limit,w_1200/q_auto/f_auto/A0063_Landscape_Sunrise_jccqpz?_a=BAMAOGUs0",
    "title": "Landscape Sunrise",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0063",
    "year": 2024,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0064_Snowfall_Landscape_lt0lxx",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--SSd_9rBd--/c_limit,w_1200/q_auto/f_auto/A0064_Snowfall_Landscape_lt0lxx?_a=BAMAOGUs0",
    "title": "Snowfall Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0064",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0065_Tulips_in_Sunset_oq6hgq",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--QV5bXcMl--/c_limit,w_1200/q_auto/f_auto/A0065_Tulips_in_Sunset_oq6hgq?_a=BAMAOGUs0",
    "title": "Tulips in Sunset",
    "category": "Landscape Paintings",
    "price": 799,
    "originalPrice": 1500,
    "sku": "SKU# A0065",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0066_Penguin_in_Snowfall_vdyfrk",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--yZ3dELye--/c_limit,w_1200/q_auto/f_auto/A0066_Penguin_in_Snowfall_vdyfrk?_a=BAMAOGUs0",
    "title": "Penguin in Snowfall",
    "category": "Animal Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0066",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0067_Christmas_Ornaments_mqaosc",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--cHgU53zT--/c_limit,w_1200/q_auto/f_auto/A0067_Christmas_Ornaments_mqaosc?_a=BAMAOGUs0",
    "title": "Christmas Ornaments",
    "category": "Festive Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0067",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0068_Lady_Watching_Sunset_hkmfjk",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--SrE4b691--/c_limit,w_1200/q_auto/f_auto/A0068_Lady_Watching_Sunset_hkmfjk?_a=BAMAOGUs0",
    "title": "Lady Watching Sunset",
    "category": "Figurative Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0068",
    "year": 2025,
    "size": "12 x 12 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Streched Canvas",
    "isSold": false
  },
  {
    "public_id": "A0069_Lady_Watching_Sunrise_uqkyuo",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--MPOWUVA2--/c_limit,w_1200/q_auto/f_auto/A0069_Lady_Watching_Sunrise_uqkyuo?_a=BAMAOGUs0",
    "title": "Lady Watching Sunrise",
    "category": "Figurative Paintings",
    "price": 1500,
    "originalPrice": 2300,
    "sku": "SKU# A0069",
    "year": 2025,
    "size": "12 x 12 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "isSold": false
  },
  {
    "public_id": "A0070_Birdy_in_Snowfall_f8pjzd",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--QW01QUQ---/c_limit,w_1200/q_auto/f_auto/A0070_Birdy_in_Snowfall_f8pjzd?_a=BAMAOGUs0",
    "title": "Birdy in Snowfall",
    "category": "Animal Paintings",
    "price": 999,
    "originalPrice": 1500,
    "sku": "SKU# A0070",
    "year": 2025,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0071_Northern_Lights_htyprc",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--alaNJkFR--/c_limit,w_1200/q_auto/f_auto/A0071_Northern_Lights_htyprc?_a=BAMAOGUs0",
    "title": "Northern Lights",
    "category": "Landscape Paintings",
    "price": 799,
    "originalPrice": 1500,
    "sku": "SKU# A0071",
    "year": 2024,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0072_Snowy_Landscape_3_zyx70i",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--6uCAHwV5--/c_limit,w_1200/q_auto/f_auto/A0072_Snowy_Landscape_3_zyx70i?_a=BAMAOGUs0",
    "title": "Snowy Landscape 3",
    "category": "Landscape Paintings",
    "price": 799,
    "originalPrice": 1500,
    "sku": "SKU# A0072",
    "year": 2024,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "A0073_Snowy_Sunset_Landscape_h9q39x",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--o2d20X8S--/c_limit,w_1200/q_auto/f_auto/A0073_Snowy_Sunset_Landscape_h9q39x?_a=BAMAOGUs0",
    "title": "Snowy Sunset Landscape",
    "category": "Landscape Paintings",
    "price": 799,
    "originalPrice": 1500,
    "sku": "SKU# A0073",
    "year": 2024,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas - Framed",
    "isSold": false
  },
  {
    "public_id": "Budha in nature",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772211569/IMG-20260227-WA0006_zxcfkj.jpg",
    "title": "☀️ Golden Serenity – Meditating Buddha Acrylic Painting ☀️",
    "category": "Spiritual Paintings",
    "price": 2800,
    "originalPrice": 5000,
    "sku": "SKU# B001",
    "year": 2026,
    "size": "12 x 16 inches",
    "description": "A radiant hand painted acrylic of a golden Buddha in deep meditation, surrounded by pure white lotus blooms and lush greenery, set against a bold backdrop of crimson red and cobalt blue. A striking fusion of stillness and vibrant colour. ✅ 100% Hand painted Acrylic on Canvas. ✅ Bold, expressive palette — gold, red & blue in harmony. ✅ Rich detailing — lotus blooms, drapery & serene expression. ✅ Perfect for living rooms, meditation spaces & statement walls. Golden calm for a colourful world. 🪷🙏",
    "medium": "Acrylic on Streched Canvas",
    "isSold": false
  }
];

// Direct fetch - no cache
export const fetchImages = async () => {
  return IMAGES;
};
